---
title: "Motor Vehicle Accidents in Victoria"
author:
- familyname: "Al-Hindi"
  othernames: "Ibrahim"
  address: Monash University
  email: "imalh2@student.monash.edu"
  correspondingauthor: true
  qualifications:  "Master of Business Analytics"
- familyname: "Chouzadjian"
  othernames: "Arek"
  address: Monash University
  email: "acho0007@student.monash.edu"
  correspondingauthor: true
  qualifications: "Master of Business Analytics"
- familyname: "Chen"
  othernames: "Kaihao"
  address: Monash University
  email: "kche154@student.monash.edu"
  correspondingauthor: true
  qualifications: "Master of Business Analytics"
department: "Department of Econometrics and Business Statistics"
organization: VicRoads
bibliography: references.bib
biblio-style: authoryear-comp
linestretch: 1.5
output:
  bookdown::pdf_document2:
    template: monashreport2.tex
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
    toc: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      eval = TRUE,
                      message = FALSE, 
                      warning = FALSE,
                      fig.width=6,
                      fig.height=4)
```

```{r libraries}
library(tidyverse)
library(lubridate)
library(janitor)
library(knitr)
library(kableExtra)
library(bookdown)
```

```{r load-data}
accidents <- read_csv("data/ACCIDENT.csv") %>%
  clean_names()

locations <- read_csv("data/ACCIDENT_LOCATION.csv") %>%
  clean_names()

nodes <- read_csv("data/NODE.csv") %>%
  clean_names()

persons <- read_csv("data/PERSON.csv") %>%
  clean_names()

vehicles <- read_csv("data/VEHICLE.csv") %>%
  clean_names()
```

```{r create-year-hour-day}
accidents <- accidents %>%
  mutate(accidentdate = dmy(accidentdate),
         Year = year(accidentdate),
         Hour = hour(accidenttime),
         Weekday = wday(accidentdate, 
                        label = TRUE,
                        abbr = FALSE))
```


# SECTION 1 - Kaihao Chen

## Accidents per year

```{r accidents-per-year}
accidents_per_year <- accidents %>%
  count(Year) %>% 
  ggplot(aes(x = Year, 
             y = n)) +
  geom_line() +
  xlab("Year(2006 ~ 2020)") +
  ylab("Number of Car Accidents") +
  geom_point() +
  geom_text(aes(label = n), 
            vjust = -1, 
            color = "black",
            size = 2) 

accidents_per_year
```


## Accidents by weekday

```{r accidents-by-day-table}
accidents_by_weekday <- accidents %>%
  count(Weekday,
        name = "Accidents")

kable(accidents_by_weekday)
```


```{r day-plot}
accidents %>%
  count(Weekday,
        name = "Accidents") %>% 
  ggplot(aes(x = Weekday, 
             y = Accidents)) +
  geom_bar(stat = "identity", 
           fill = "#999999") +
  ylab("Number of Car Accidents") +
  geom_text(aes(label = Accidents), 
            vjust = -1, 
            color = "black", 
            size = 3)
```


## Accidents by hour

```{r accidents-by-hour-plot}
accidents_by_hour <- accidents %>%
  count(Hour,
        name = "Accidents") 

accidents_by_hour %>%
  ggplot(aes(x = Hour, 
             y = Accidents)) + 
  geom_line() +
  xlab("Time") +
  ylab("Number of Car Accidents") +
  geom_point() +
  geom_text(aes(label = Accidents), 
            vjust = -1, 
            color = "black",
            size = 2) 

```



## Deaths by hour

```{r deaths-by-hour}
deaths_by_hour <- accidents %>%
  group_by(Hour) %>%
  tally(no_persons_killed,
        name = "Deaths")
```

```{r deaths-per-accident-by-hour}
deaths_per_accident_by_hour <- accidents_by_hour %>%
  left_join(deaths_by_hour) %>%
  mutate(Deaths_per_accident = round(Deaths/Accidents, digit = 4))
```

```{r deaths per accident by hour plot}
deaths_per_accident_by_hour %>%
  ggplot(aes(x = Hour, 
             y = Deaths_per_accident)) +
  geom_line() +
  xlab("Time") +
  ylab("Death Rate of Car Accidents") +
  geom_point() +
  geom_text(aes(label = Deaths_per_accident), 
            vjust = -1, 
            color = "black",
            size = 2) 
```



